
%dw 2.0
output application/java 
---
{
  getRecordsResult : {
    active : true,
    activity_due : "",
    additional_assignee_list : "vel",
    approval : "architecto",
    approval_set : "totam",
    assigned_to : "iure",
    assignment_group : "nulla",
    business_duration : "architecto",
    business_impact : "rem",
    business_service : "nostrum",
    business_stc : 75,
    calendar_duration : "esse",
    calendar_stc : 41,
    caller_id : "8dce6f3479864e35a43",
    category : "ullam",
    cause : "dolore",
    caused_by : "ad",
    child_incidents : 72,
    close_code : "qui",
    close_notes : "qui",
    closed_at : "velit,",
    closed_by : "aspernatur",
    cmdb_ci : "consectetur,",
    comments_and_work_notes : "voluptatem",
    company : "magni",
    contact_type : "reprehenderit",
    contract : "quo",
    correlation_display : "dolorem",
    correlation_id : "2ddab839b0e942888a8",
    delivery_plan : "Nemo",
    delivery_task : "dolores",
    description : "aperiam, est ipsum vel sit dolorem minima nesciunt. consectetur dolorem sed sit iste Quis eos nesciunt. ",
    due_date : "consequatur?",
    escalation : 67,
    expected_start : "nisi",
    follow_up : "et",
    group_list : "esse",
    hold_reason : 81,
    impact : 4,
    incident_state : 9,
    knowledge : false,
    location : "voluptate",
    made_sla : false,
    notify : 49,
    number : "est",
    opened_at : "velit",
    opened_by : "dolor",
    order : 86,
    origin_id : "02b88536566b4b849b1",
    origin_table : "velit,",
    parent : "suscipit",
    parent_incident : "laboriosam,",
    priority : 24,
    problem_id : "e045991a2a9d4fc8994",
    reassignment_count : 20,
    reopen_count : 19,
    reopened_by : "modi",
    reopened_time : "tempora",
    resolved_at : "nisi",
    resolved_by : "eiusmod",
    rfc : "dolor",
    route_reason : 38,
    service_offering : "adipiscing",
    severity : 76,
    short_description : "proident, laborum. molestiae occaecat quaerat adipisci Ut consequatur, iste et ",
    sla_due : "dolore",
    state : 59,
    subcategory : "exercitationem",
    sys_class_name : "amet,",
    sys_created_by : "odit",
    sys_created_on : "illo",
    sys_domain : "consectetur",
    sys_domain_path : "enim",
    sys_id : "457e6a1a14a94f46977",
    sys_mod_count : 45,
    sys_updated_by : "nostrud",
    sys_updated_on : "eos",
    task_effective_number : "quis",
    time_worked : "sed",
    universal_request : "non",
    upon_approval : "eos",
    upon_reject : "dolore",
    urgency : 8,
    user_input : "non",
    watch_list : "sequi",
    work_end : "voluptate",
    work_notes_list : "sit",
    work_start : "eos",
  },
}
